### ISSUE TITLE
ERROR: Running the `get-hooks` hook (sdk_config_load_error)

### ISSUE THREAD

**Issue by cbullard-dev** [slack-samples/bolt-js-starter-template#57] opened 2023-09-26 00:29 UTC
I received the following error when running the `slack run` command using the `bolt-js-starter-template -b future`

Slack Version: `Using slack v2.9.1`

```
slack run
Check {REDACTED} for full error logs

🚫 There was an error while reading the Slack Configuration file (`slack.json`) or running the `get-hooks` hook (sdk_config_load_error)

Error Details:

1: There was an error while reading the Slack Configuration file (`slack.json`) or running the `get-hooks` hook (sdk_config_load_error)
Suggestion: Run `slack doctor` to check that your system dependencies are up-to-date.


Suggestion:

Run `slack doctor` to check that your system dependencies are up-to-date.
```

I then tried running the `slack doctor`

```
slack doctor
Check {REDACTED} for full error logs

🚫 There was an error while reading the Slack Configuration file (`slack.json`) or running the `get-hooks` hook (sdk_config_load_error)

Error Details:

1: There was an error while reading the Slack Configuration file (`slack.json`) or running the `get-hooks` hook (sdk_config_load_error)
Suggestion: Run `slack doctor` to check that your system dependencies are up-to-date.


Suggestion:

Run `slack doctor` to check that your system dependencies are up-to-date.
```

This is the content of the `slack.json` file
```
{
  "hooks": {
    "get-hooks": "npx -q --no-install -p @slack/bolt slack-cli-get-hooks"
  }
}
```

I am also unable to run `slack version` or any slack CLI command inside the same directory as they all fail with the same error. Running `slack doctor` outside of the directory works without any issues and I proceed as normal.

**Comment by zimeg** [comment] 2023-09-28 02:12
:wave: We've determined this was caused by extra debugging information being output by the hooks command, causing this error between the hook and CLI.

Going to close this issue now, but for future reference and readers this can be debugged by running the following command from your project directory in the terminal:

```sh
$ npx -q --no-install -p @slack/bolt slack-cli-get-hooks
```

With an ideal output looking something like...

```
{"hooks":{"get-manifest":"npx -q --no-install -p @slack/bolt slack-cli-get-manifest","check-update":"npx -q --no-install -p @slack/bolt slack-cli-check-update","start":"npx -q --no-install -p @slack/bolt slack-cli-start"},"config":{"watch":{"filter-regex":"^manifest\\.(ts|js|json)$","paths":["."]},"sdk-managed-connection-enabled":true}}
```

**Closed by zimeg** 2023-09-28 02:12 UTC
Labels: bug, question
